parameters:

  flood_control.class:            dmFloodControl
  flood_control.options:
    entity_model:                 DmFloodControlEntity

services:

  flood_control:
    class:                        %dm_flood_control.class%
    arguments:                    [ @request, %dm_flood_control.options% ]